FROM golang:1.23 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o listener_app listener/main.go


FROM debian:latest
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates
COPY --from=builder /app/listener_app .
ENTRYPOINT ["./listener_app"]