FROM golang:1.23 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o web_app web/main.go


FROM debian:latest
WORKDIR /app
COPY --from=builder /app/web_app .
CMD ["./web_app"]