name: web
on:
  push:
    branches:
      - build

jobs:
  build-listener-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile_listener
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/blackmorse/tonarb/tonarb-listener:latest